name: Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production

      - name: Optimize images
        run: |
          cd dist
          find . -type f -name "*.png" -exec convert {} -strip -quality 85 {} \;
          find . -type f -name "*.jpg" -exec convert {} -strip -quality 85 {} \;
          find . -type f -name "*.jpeg" -exec convert {} -strip -quality 85 {} \;
          find . -type f -name "*.webp" -exec convert {} -strip -quality 85 {} \;

      - name: Deploy to SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./dist/
          server-dir: /home2/smipmxco/public_html/
          dangerous-clean-slate: true
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            README.md
            .env*